package com.company.dao;

import com.company.dao.base.Book;
import com.company.dao.service.ServiceBook;

import java.sql.Date;
import java.time.LocalDate;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class App {


    public static void main(String[] args) throws Exception {
        Scanner in = new Scanner(System.in);
        ServiceBook serviceBook = new ServiceBook();
        boolean exit = true;


        System.out.println("Commands: " +
                "\n - all - show all books;" +
                "\n - get{ID} - detailed information about the book;" +
                "\n - add - add book (autogenerated ID)" +
                "\n - update{ID} - update book information (by Id)" +
                "\n - delete{ID} - delete book;" +
                "\n - getisbn{ISBN} - Get Book by ISBN;" +
                "\n - exit - exit; " +
                "\n Enter the command:");
        try {
            while (exit) {
                String commandConsole = in.nextLine();
                commandConsole = commandConsole.toLowerCase();

                if (commandConsole.matches("all")) {
                    serviceBook.getAllBooks();
                } else if (Pattern.matches("get\\W\\d*\\W", commandConsole)) {
                    Pattern patternGetId = Pattern.compile("\\d+");
                    Matcher matcher = patternGetId.matcher(commandConsole);
                    if (matcher.find()) {
                        serviceBook.getBookById(Long.parseLong(matcher.group()));
                    }
                } else if (Pattern.matches("add", commandConsole)) {
                    Book book = new Book();

                    System.out.println("Write BookStore BookName:");
                    book.setBookname(in.nextLine());
                    System.out.println("Write BookStore NameAuthor:");
                    book.setNameauthor(in.nextLine());
                    System.out.println("Write BookStore DatePurchase (yyyy-MM-dd format):");
                    book.setDatepurchase(Date.valueOf(LocalDate.parse(in.nextLine())));
                    System.out.println("Write BookStore status price: ");
                    book.setStatus(in.nextLine());
                    System.out.println("Write BookStore price: ");
                    book.setPrice(in.nextInt());
                    System.out.println("Write BookStore ISBN: ");
                    book.setIsbn(in.nextInt());

                    serviceBook.addBookById(book);
                } else if (Pattern.matches("update\\W\\d*\\W", commandConsole)) {
                    Book book = new Book();
                    Pattern patternUpdateId = Pattern.compile("\\d+");
                    Matcher matcher = patternUpdateId.matcher(commandConsole);
                    if (matcher.find()) {
                        book.setId(Long.parseLong(matcher.group()));
                        System.out.println("Write BookStore BookName:");
                        book.setBookname(in.nextLine());
                        System.out.println("Write BookStore NameAuthor:");
                        book.setNameauthor(in.nextLine());
                        System.out.println("Write BookStore DatePurchase (yyyy-MM-dd format):");
                        book.setDatepurchase(Date.valueOf(LocalDate.parse(in.nextLine())));
                        System.out.println("Write BookStore status price: ");
                        book.setStatus(in.nextLine());
                        System.out.println("Write BookStore price: ");
                        book.setPrice(in.nextInt());
                        System.out.println("Write BookStore ISBN: ");
                        book.setIsbn(in.nextInt());

                        serviceBook.updateBookById(book);
                    }
                } else if (Pattern.matches("delete\\W\\d*\\W", commandConsole)) {
                    Pattern patternDeleteId = Pattern.compile("\\d+");
                    Matcher matcher = patternDeleteId.matcher(commandConsole);
                    if (matcher.find()) {
                        serviceBook.deleteBookById(Long.parseLong(matcher.group()));
                    }
                } else if (commandConsole.matches("exit")) {
                    exit = false;
                } else if (Pattern.matches("getisbn\\W\\d*\\W", commandConsole)) {
                    Book book = new Book();
                    Pattern patternGetByISBN = Pattern.compile("\\d+");
                    Matcher matcher = patternGetByISBN.matcher(commandConsole);
                    if (matcher.find()) {
                        serviceBook.getBookByISBN(Integer.parseInt(matcher.group()));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            in.close();
            System.out.println("Thank you! GoodBye!");
        }
    }
}



