package com.company.dao;

import com.company.dao.base.Book;
import com.company.dao.service.ServiceUser;

import java.sql.Date;
import java.time.LocalDate;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class App {


    public static void main(String[] args) throws Exception {
        Scanner in = new Scanner(System.in);
        ServiceUser serviceUser = new ServiceUser();
        String exit = "";


        System.out.println("Commands: " +
                "\n - all - show all books;" +
                "\n - get{ID} - detailed information about the book;" +
                "\n - add - add book (autogenerated ID)" +
                "\n - delete{ID} - delete book;" +
                "\n - exit - exit; " +
                "\n Enter the command:");

        while (exit != "exit") {
            String commandConsole = in.nextLine();
            commandConsole = commandConsole.toLowerCase();

            if (commandConsole.matches("all")) {
                serviceUser.getAllBooks();
            } else if (Pattern.matches("get\\S*", commandConsole)) {
                Pattern patternGetId = Pattern.compile("\\d+");
                Matcher matcher = patternGetId.matcher(commandConsole);
                if (matcher.find()) {
                    serviceUser.getBooksById(Long.parseLong(matcher.group()));
                }
            } else if (Pattern.matches("add", commandConsole)) {
                Book book = new Book();

                System.out.println("Write BookStore BookName:");
                book.setBookname(in.nextLine());
                System.out.println("Write BookStore NameAuthor:");
                book.setNameaytor(in.nextLine());
                System.out.println("Write BookStore DatePurchase (yyyy-MM-dd format):");
                book.setDatepurchase(Date.valueOf(LocalDate.parse(in.nextLine())));
                System.out.println("Write BookStore status price: ");
                book.setStatus(in.nextLine());
                System.out.println("Write BookStore price: ");
                book.setPrice(in.nextInt());

                serviceUser.addBookById(book);
            } else if (Pattern.matches("delete\\S*", commandConsole)) {
                Pattern patternDeleteId = Pattern.compile("\\d+");
                Matcher matcher = patternDeleteId.matcher(commandConsole);
                if (matcher.find()) {
                    serviceUser.deleteBookById(Long.parseLong(matcher.group()));
                }
            }
        }
    }

}



